### PR TITLE
Support for the new functions SLEEP and GET_BUSY

### PR DESCRIPTION
**Pull request by sekdiy**
I've added support for the newer I2C commands 0x08 (SLEEP) and 0x09 (GET_BUSY) and extended the documentation.

See: https://github.com/Miceuz/i2c-moisture-sensor/commit/99f2a3d5d41b26625d6612802b686a42a0119094

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you. I will merge it later and would add the info that the two new functions are available beginning with FW 2.3 so that people are not using it before and wonder.

And thanks for the Keyword-Thing ... I must be too tired that day ;-)

**Comment by sekdiy** [comment]
I'm having a couple more sensors on the way that Albertas said to have the most recent firmware. 
I'll test and report back with a comparison of how the functions behave with older and newer versions, respectively.

Should it turn out to be problematic, I could as well add a version switch (i.e. using getVersion()).

**Comment by Apollon77** [comment]
great!
I have merged it and will prepare the 1.1.0 in the background, so you can use the master branch from here.
I wait with oficial release till you tested it (because I only have sensors with FW 2.2 :-)

**Comment by Apollon77** [comment]
Did you got the sensors and could test?

**Comment by sekdiy** [comment]
~~Still no delivery, sorry.~~

I finally received two sensors this week.

Will report back as soon as I have a chance to test them...

**Comment by Apollon77** [comment]
Do you had the chance to check?

**Comment by sekdiy** [comment]
Well, sort of, but it's not yet conclusive to me.

Apparently there's no obvious issue with the SLEEP and GET_BUSY commands, both with the old and new sensors.
Older firmware versions implicitly SLEEP after every measurement, newer versions explicitly wait for the I2C SLEEP command.
Then again, all the firmware versions gracefully ignore unknown I2C commands.
Thus, sending a SLEEP command to a sensor with an unknown firmware version should result in the same sleeping behaviour for all firmware versions. :)

I'm thinking, maybe an example that makes explicit use of the sleep command would be a good idea. Otherwise users might run into issues with changed current consumption without noticing.

But I'm having a suspicion that the sensor isn't exactly invariant to the way it is used.
I get different values dependent on wether I poll only one figure (e.g. moisture) or multiple (e.g. moisture, temperature and light level) while sleeping periodically.

The following screenshot shows moisture (capacitance) in a steady state (no significant moisture changes) while being switched from sleep to awake and also providing temperature and light level measurements (with temperature and light exposure actually changing).

It should be noted that when only polling capacitance (and not sleeping inbetween), noise and repeatability are much, much better.

screen shot 2016-07-14 at 12 18 32

Admittedly this is not an issue with this very library, but with the sensor's firmware.
So one could argue that nothing stands in the way of integrating this change and making the release.

**Comment by Apollon77** [comment]
Thank you for all the details.
I changed the Read-Sensor example to use the both new functions. Can you test it please? I have no unused Arduino at the moment (need to order a new one) :(

**Comment by Apollon77** [comment]
officially released

**Pull request merged**
